#!/bin/sh
# Install root-owned at /usr/local/sbin/cashbasis-restart-apache (mode 0755).
set -eu
test "$#" -eq 0
/usr/sbin/apache2ctl configtest
/usr/bin/systemctl restart apache2
/usr/bin/systemctl is-active --quiet apache2
